#!/usr/bin/env node
// Fails when the sample bundle is not where the site serves it from.
//
// The sample is data rather than source: it is regenerated by `scripts/make-sample.mjs` and has to
// be committed for the site to carry it, and a build that drops the folder looks fine everywhere
// except on the live site, where it is a 404. Checked here, after the build, so that mistake stops
// the deploy instead of reaching a reader.
//
// Run: node scripts/check-sample.mjs [directory]
import { existsSync, readFileSync, statSync } from "node:fs";
import { join } from "node:path";

const directory = process.argv[2] ?? join("dist", "sample");
const listing = join(directory, "index.json");

if (!existsSync(listing)) {
  console.error(`the sample is missing: ${listing} does not exist`);
  process.exit(1);
}

const { files } = JSON.parse(readFileSync(listing, "utf8"));
if (!Array.isArray(files) || files.length === 0) {
  console.error(`the sample lists no files: ${listing}`);
  process.exit(1);
}

const missing = files.filter((name) => {
  const file = join(directory, name);
  return !existsSync(file) || statSync(file).size === 0;
});

if (missing.length > 0) {
  console.error(`the sample lists files that are missing from ${directory}:`);
  for (const name of missing) console.error(`  ${name}`);
  process.exit(1);
}

console.log(`the sample is in place: ${files.length} files in ${directory}`);
