import type { BundleFile } from "./bundle-file";

/** Where the generated sample bundle is published, relative to the deployed base path. */
const SAMPLE_DIRECTORY = "sample";

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

async function fetchBytes(url: string): Promise<Uint8Array> {
  const response = await fetch(url);
  if (!response.ok) throw new Error(`${url} returned ${response.status}`);
  return new Uint8Array(await response.arrayBuffer());
}

/** The file names listed in the bundle's own index. */
function filesIn(listing: unknown): readonly string[] {
  if (!isRecord(listing)) return [];

  const { files } = listing;
  if (!Array.isArray(files)) return [];
  return files.filter((name): name is string => typeof name === "string");
}

/**
 * Reads the sample bundle that ships alongside the viewer.
 *
 * It is generated by `scripts/make-sample.mjs` — not taken from a public dental dataset, whose
 * licences do not allow redistribution — and it goes through the same reader as a dropped
 * folder, so trying the sample exercises the real path. Fetched relative to the base path, so it
 * works from a GitHub Pages subdirectory as well as from the root.
 */
export async function readSampleBundle(): Promise<readonly BundleFile[]> {
  const base = `${import.meta.env.BASE_URL}${SAMPLE_DIRECTORY}/`;

  const listing = await fetch(`${base}index.json`);
  if (!listing.ok)
    throw new Error(`the sample bundle is missing (${listing.status})`);

  const names = filesIn(await listing.json());
  if (names.length === 0) throw new Error("the sample bundle lists no files");

  return Promise.all(
    names.map(async (name) => ({
      path: name,
      bytes: await fetchBytes(`${base}${name}`),
    })),
  );
}
